// Generated by CoffeeScript 1.6.2
(function() {
  define(['jquery', 'js-fixtures'], function($, fixtures) {
    return describe("Labels", function() {
      var $label, $textControl, collection, control, simpleForm, translatedSimpleForm, translations, translator,
        _this = this;

      simpleForm = null;
      translatedSimpleForm = null;
      $textControl = null;
      collection = ['male', 'female'];
      control = function(options) {
        if (options == null) {
          options = {};
        }
        return simpleForm.input('user', 'name', options);
      };
      $label = function(options) {
        if (options == null) {
          options = {};
        }
        return $(control(options)).find('label');
      };
      translations = {
        simple_form: {
          hints: {
            user: {
              name: 'translated hints: Name'
            }
          },
          labels: {
            user: {
              name: 'translated labels: Name'
            }
          },
          placeholders: {
            user: {
              name: 'translated labels: Name'
            }
          }
        }
      };
      translator = function(attr) {
        var attrs, trans;

        attrs = attr.split('.');
        attrs.push(attr);
        trans = _.clone(translations);
        while (attrs.length) {
          trans = trans[attrs.shift()];
          if (_.isString(trans) || trans === undefined || trans === null) {
            break;
          }
        }
        return trans;
      };
      beforeEach(function() {
        simpleForm = new ST.SimpleForm();
        return translatedSimpleForm = new ST.SimpleForm({
          translator: translator
        });
      });
      afterEach(function() {
        return fixtures.cleanUp();
      });
      return describe("test label options", function() {
        it("should set default label to attributeName", function() {
          return $label().text().should.eq('name');
        });
        it("should set custom label text", function() {
          return $label({
            label: "hello world"
          }).text().should.eq('hello world');
        });
        it("should render without label", function() {
          return $(control({
            label: false
          })).find(".label").length.should.eq(0);
        });
        return it("should render translated label", function() {
          var ct;

          ct = translatedSimpleForm.input('user', 'name');
          return $(ct).find('label').text().should.eq('translated labels: Name');
        });
      });
    });
  });

}).call(this);
